# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pr:
- master

stages:
  - stage: Build_Images
    displayName: Build
          
    jobs:
    - job: Build
      strategy:
        matrix:
          mono604:
            monoVersion: 6.4
          mono600:
            monoVersion: 6.0
          mono520:
            monoVersion: 5.20
          mono518:
            monoVersion: 5.18
          mono516:
            monoVersion: 5.16
          mono514:
            monoVersion: 5.14
          mono512:
            monoVersion: 5.12
          mono510:
            monoVersion: 5.10
          mono508:
            monoVersion: 5.8
          mono504:
            monoVersion: 5.4
          mono500:
            monoVersion: 5.0

      pool:
        vmImage: ubuntu-16.04

      steps:
      - checkout: self
        submodules: true
        fetchDepth: 1
      - bash: ./generate_images.sh -v $(monoVersion)
        displayName: Build Mono $(monoVersion)
      - bash: |
          echo $DOCKER_PASSWORD | sudo docker login -username lidarrbuild --password-stdin
          sudo docker push lidarr/testimages:mono-$(monoVersion)
        condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
        env:
          DOCKER_PASSWORD: $(dockerPassword)
